build:
  nodes:
    postgres:
      services:
        # For available tags, see https://hub.docker.com/_/postgres/
        postgres: 10

    backend:
      root_path: './server'

      environment:
        node: v10
      project_setup:
        before:
          - command: yarn
      tests:
        override:
          - command: 'yarn scrutinizer'
            coverage:
              file: 'coverage/clover.xml'
              format: 'clover'

    frontend:
      root_path: './client'

      project_setup:
        before:
          - command: yarn
      tests:
        override:
          - command: 'yarn test'

filter:
  excluded_paths:
    - 'coverage'
    - 'dist'
    - 'node_modules'
    - 'tests'

checks:
  javascript:
    code_rating: true
    duplicate_code: true
