language: node_js

node_js:
  - 'node'
  - '10'
  - '8'

services:
  - postgresql

env:
  - TEST_DIR=server
  - TEST_DIR=client

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - cd server && cp ormconfig.travis.json ormconfig.json
  - cd ..

script: cd $TEST_DIR && yarn && yarn travis
