language: node_js

node_js:
  - 'node'
  - '10'
  - '8'

services:
  - mysql

env:
  - TEST_DIR=server
  - TEST_DIR=client

before_script:
  - mysql -e 'create database travis_ci_test  DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_general_ci;'
  - mysql -u root -e "create user test identified by 'test'; grant all on travis_ci_test.* to test;"
  - mysql -u root -e "create user test@localhost identified by 'test'; grant all on travis_ci_test.* to test@localhost;"
  - mysql -u test -p'test' -e 'show databases'
  - cd server
  - sleep 60
  - cp ormconfig.travis.json ormconfig.json
  - cd ..

script:
  - cd $TEST_DIR && yarn && yarn travis
