language: node_js

node_js:
  - 'node'
  - '10'
  - '8'

services:
  - postgresql

env:
  - TEST_DIR=server
  - TEST_DIR=client

before_script:
  - sudo service mysql stop
  - psql -c "CREATE DATABASE travis_ci_test;" -U postgres
  - psql -c "CREATE USER test WITH PASSWORD 'test';" -U postgres
  - psql -d -c "create EXTENSION pgcrypto;"
  - cd server
  - sleep 60
  - cp ormconfig.travis.json ormconfig.json
  - cd ..

script:
  - cd $TEST_DIR && yarn && yarn travis
