language: node_js

node_js:
  - 'node'
  - '10'
  - '8'

services:
  - docker

env:
  - TEST_DIR=server
  - TEST_DIR=client

before_script:
  - sudo service mysql stop
  - sudo service postgresql stop
  - cd server && docker-compose up -d
  - cp ormconfig.travis.json ormconfig.json
  - cd ..

script:
  - cd $TEST_DIR &
  - yarn &
  - sleep 20
  - yarn travis
