language: node_js

node_js:
  - 'node'
  - '10'
  - '8'

services:
  - docker

env:
  - TEST_DIR=server
  - TEST_DIR=client

before_script:
  - cd server
  - docker-compose up -d
  - sleep 70
  - docker ps
  - cp ormconfig.travis.json ormconfig.json
  - cd ..

script:
  - cd $TEST_DIR && yarn && yarn travis
