language: node_js

node_js:
  - 'node'
  - '10'
  - '8'

services:
  - mysql

env:
  - TEST_DIR=server
  - TEST_DIR=client

before_script:
  - mysql -e 'create database travis_ci_test;'
  - mysql -u root -e "create user 'test'@'localhost' identified by 'test';"
  - mysql -u root -e "grant all privileges on travis_ci_test.* to 'test'@'localhost';"
  - cd server
  - sleep 200
  - cp ormconfig.travis.json ormconfig.json
  - cd ..

script:
  - cd $TEST_DIR && yarn && yarn travis
