version: '3'

services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=travis_ci_test
      - MYSQL_USER=test
      - MYSQL_PASSWORD=test
    ports:
      - '5432:3306'
