version: '3'
services:
  # mysql
  mysql:
    image: 'mysql'
    container_name: 'typeorm-mysql'
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: 'admin'
      MYSQL_USER: 'test'
      MYSQL_PASSWORD: 'test'
      MYSQL_DATABASE: 'test'
