version: '3'
services:
  # postgres
  postgres:
    image: 'postgres'
    container_name: 'typeorm-postgres'
    ports:
      - '3306:3306'
    environment:
      POSTGRES_ROOT_PASSWORD: 'admin'
      POSTGRES_USER: 'root'
      POSTGRES_PASSWORD: '12345'
      POSTGRES_DATABASE: 'ramverk2_test'
