version: '3'
services:
  # mysql
  mysql:
    image: 'mysql:latest'
    container_name: 'typeorm-mysql'
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: 'admin'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: '12345'
      MYSQL_DATABASE: 'ramverk2_test'
