version: '3'
services:
  # postgres
  postgres:
    image: 'postgres'
    container_name: 'typeorm-postgres'
    ports:
      - '3306:3306'
    environment:
      POSTGRES_ROOT_PASSWORD: 'admin'
      POSTGRES_USER: 'test'
      POSTGRES_PASSWORD: 'test'
      POSTGRES_DATABASE: 'test'
